<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>How can Auth Tokens be used securly in core.http runner?</title>
    <link>https://forum.stackstorm.com/t/how-can-auth-tokens-be-used-securly-in-core-http-runner/1749</link>
    <description>Hi,

I want to make an API call by using an auth token which should not be passed as cleartext to the logs.
The API request is working if I pass the Token via header in the format below:
```
{&quot;Authorization&quot;:&quot;TokenValueXYZ&quot;}
```

But if I do it like this, it&#39;s value is cleartext leaked to the Stackstorm logs. I tried to use &quot;auth&quot; parameter which fails all the time even if you use the example &#39;x-auth-token=XYZ&#39;.

Always an error like this is received:
```
&#39;str&#39; object is not callable
  File &quot;/opt/stackstorm/st2/lib/python3.6/site-packages/st2actions/container/base.py&quot;, line 128, in _do_run
    (status, result, context) = runner.run(action_params)
  File &quot;/opt/stackstorm/st2/lib/python3.6/site-packages/http_runner/http_runner.py&quot;, line 113, in run
    result = client.run()
  File &quot;/opt/stackstorm/st2/lib/python3.6/site-packages/http_runner/http_runner.py&quot;, line 262, in run
    verify=self.verify
  File &quot;/opt/stackstorm/st2/lib/python3.6/site-packages/requests/api.py&quot;, line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File &quot;/opt/stackstorm/st2/lib/python3.6/site-packages/requests/sessions.py&quot;, line 516, in request
    prep = self.prepare_request(req)
  File &quot;/opt/stackstorm/st2/lib/python3.6/site-packages/requests/sessions.py&quot;, line 459, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File &quot;/opt/stackstorm/st2/lib/python3.6/site-packages/requests/models.py&quot;, line 318, in prepare
    self.prepare_auth(auth, url)
  File &quot;/opt/stackstorm/st2/lib/python3.6/site-packages/requests/models.py&quot;, line 549, in prepare_auth
    r = auth(self)
```

Is there any possibility to to use a token in a safe way? BasicAuth is not possible.

Thanks.</description>
    
    <lastBuildDate>Mon, 28 Jun 2021 08:53:49 +0000</lastBuildDate>
    <category>Uncategorized</category>
    <atom:link href="https://forum.stackstorm.com/t/how-can-auth-tokens-be-used-securly-in-core-http-runner/1749.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>How can Auth Tokens be used securly in core.http runner?</title>
        <dc:creator><![CDATA[wingi]]></dc:creator>
        <description><![CDATA[
            <p>Hi,</p>
<p>I want to make an API call by using an auth token which should not be passed as cleartext to the logs.<br>
The API request is working if I pass the Token via header in the format below:</p>
<pre><code class="lang-auto">{"Authorization":"TokenValueXYZ"}
</code></pre>
<p>But if I do it like this, it’s value is cleartext leaked to the Stackstorm logs. I tried to use “auth” parameter which fails all the time even if you use the example ‘x-auth-token=XYZ’.</p>
<p>Always an error like this is received:</p>
<pre><code class="lang-auto">'str' object is not callable
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2actions/container/base.py", line 128, in _do_run
    (status, result, context) = runner.run(action_params)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/http_runner/http_runner.py", line 113, in run
    result = client.run()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/http_runner/http_runner.py", line 262, in run
    verify=self.verify
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/requests/sessions.py", line 459, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/requests/models.py", line 318, in prepare
    self.prepare_auth(auth, url)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/requests/models.py", line 549, in prepare_auth
    r = auth(self)
</code></pre>
<p>Is there any possibility to to use a token in a safe way? BasicAuth is not possible.</p>
<p>Thanks.</p>
          <p><a href="https://forum.stackstorm.com/t/how-can-auth-tokens-be-used-securly-in-core-http-runner/1749/1">Read full topic</a></p>
        ]]></description>
        <link>https://forum.stackstorm.com/t/how-can-auth-tokens-be-used-securly-in-core-http-runner/1749/1</link>
        <pubDate>Mon, 28 Jun 2021 08:53:49 +0000</pubDate>
        <guid isPermaLink="false">forum.stackstorm.com-post-1749-1</guid>
        <source url="https://forum.stackstorm.com/t/how-can-auth-tokens-be-used-securly-in-core-http-runner/1749.rss">How can Auth Tokens be used securly in core.http runner?</source>
      </item>
  </channel>
</rss>
